name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Build for multi-platform
        run: |
          $platforms = "linux/amd64", "darwin/amd64", "linux/arm", "windows/amd64"
          foreach ($platform in $platforms) {
            $split = $platform.split('/')
            $env:GOOS = $split[0]
            $env:GOARCH = $split[1]
            if ($env:GOOS -eq "windows") {
                $ext = ".exe"
            } else {
                $ext = ""
            }
            $buildPath = "handy-sshd-$env:GOOS-$env:GOARCH"
            mkdir $buildPath
            go build -o "${buildPath}/handy-sshd${ext}" main/main.go
            Compress-Archive -Path $buildPath -DestinationPath "$buildPath.zip"
          }
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multi-platform-binaries
          path: |
            handy-sshd-linux-amd64.zip
            handy-sshd-darwin-amd64.zip
            handy-sshd-linux-arm.zip
            handy-sshd-windows-amd64.zip